import {
  MEMORY_OBJECT_KINDS,
  MEMORY_RELATION_TYPES,
  RELATIONSHIP_EXTRA_INFO_KEYS,
} from "./memory.ts";
import { MEMORY_OPERATION_KINDS } from "./history.ts";
import {
  AGENT_TYPES,
  ADMIN_MEMORY_ACTIONS,
  MEMORY_ACTIONS,
} from "./rbac.ts";

const nonEmptyString = {
  type: "string",
  minLength: 1,
} as const;

const timestamp = {
  type: "string",
  format: "date-time",
} as const;

const stringArray = {
  type: "array",
  items: { type: "string" },
  uniqueItems: true,
} as const;

const relationEndpointKinds = MEMORY_OBJECT_KINDS.filter(
  (kind) => kind !== "memory_relation",
);

export const CONTRACT_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://team-memory-rbac.dev/contracts/v1/schema.json",
  title: "Team Memory RBAC Contracts",
  type: "object",
  $defs: {
    MemoryRelationType: {
      type: "string",
      enum: MEMORY_RELATION_TYPES,
    },
    MemoryObjectKind: {
      type: "string",
      enum: MEMORY_OBJECT_KINDS,
    },
    MemoryAction: {
      type: "string",
      enum: MEMORY_ACTIONS,
    },
    AdminMemoryAction: {
      type: "string",
      enum: ADMIN_MEMORY_ACTIONS,
    },
    User: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "displayName",
        "status",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        displayName: nonEmptyString,
        email: { type: "string" },
        status: { enum: ["active", "disabled"] },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    AgentIdentity: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "ownerUserId",
        "agentType",
        "displayName",
        "status",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        ownerUserId: nonEmptyString,
        agentType: { enum: AGENT_TYPES },
        displayName: nonEmptyString,
        status: { enum: ["active", "disabled"] },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    PermissionConstraint: {
      type: "object",
      additionalProperties: false,
      properties: {
        allowedTags: stringArray,
        requiredTags: stringArray,
        deniedTags: stringArray,
        allowedRelationTypes: {
          type: "array",
          items: { $ref: "#/$defs/MemoryRelationType" },
          uniqueItems: true,
        },
        deniedRelationTypes: {
          type: "array",
          items: { $ref: "#/$defs/MemoryRelationType" },
          uniqueItems: true,
        },
        allowRootEntityMutation: { type: "boolean" },
        maxRelationExpansionDepth: {
          type: "integer",
          minimum: 0,
        },
        requireHumanApproval: { type: "boolean" },
      },
    },
    Permission: {
      type: "object",
      additionalProperties: false,
      required: ["action", "resourceKind"],
      properties: {
        action: { $ref: "#/$defs/MemoryAction" },
        resourceKind: { $ref: "#/$defs/MemoryObjectKind" },
        tagsAny: stringArray,
        tagsAll: stringArray,
        relationTypes: {
          type: "array",
          items: { $ref: "#/$defs/MemoryRelationType" },
          uniqueItems: true,
        },
        taskScope: stringArray,
      },
    },
    Role: {
      type: "object",
      additionalProperties: false,
      required: ["id", "name", "kind", "permissions", "status"],
      properties: {
        id: nonEmptyString,
        name: nonEmptyString,
        kind: { enum: ["built_in", "custom"] },
        permissions: {
          type: "array",
          minItems: 1,
          items: { $ref: "#/$defs/Permission" },
        },
        status: { enum: ["active", "disabled"] },
      },
    },
    UserRootRoleAssignment: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "userId",
        "rootEntityId",
        "roleId",
        "assignedBy",
        "assignedAt",
        "status",
      ],
      properties: {
        id: nonEmptyString,
        userId: nonEmptyString,
        rootEntityId: nonEmptyString,
        roleId: nonEmptyString,
        assignedBy: nonEmptyString,
        assignedAt: timestamp,
        status: { enum: ["active", "revoked"] },
        revokedAt: timestamp,
        expiresAt: timestamp,
      },
    },
    TaskScope: {
      type: "object",
      additionalProperties: false,
      required: ["rootEntityId"],
      properties: {
        rootEntityId: nonEmptyString,
        allowedEntityIds: stringArray,
        deniedEntityIds: stringArray,
        allowedTags: stringArray,
        deniedTags: stringArray,
        allowedResourceIds: stringArray,
        deniedResourceIds: stringArray,
        relationExpansionPolicy: {
          type: "object",
          additionalProperties: false,
          properties: {
            allowedRelationTypes: {
              type: "array",
              items: { $ref: "#/$defs/MemoryRelationType" },
              uniqueItems: true,
            },
            maxDepth: {
              type: "integer",
              minimum: 0,
            },
            allowRequiredDependencies: { type: "boolean" },
          },
        },
      },
    },
    AgentDelegation: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "ownerUserId",
        "rootEntityId",
        "permissions",
        "delegatedBy",
        "delegatedAt",
        "status",
      ],
      properties: {
        id: nonEmptyString,
        agentId: nonEmptyString,
        ownerUserId: nonEmptyString,
        rootEntityId: nonEmptyString,
        permissions: {
          type: "array",
          minItems: 1,
          items: { $ref: "#/$defs/Permission" },
        },
        delegatedBy: nonEmptyString,
        delegatedAt: timestamp,
        status: { enum: ["active", "revoked"] },
        revokedAt: timestamp,
        expiresAt: timestamp,
      },
    },
    PrincipalContext: {
      type: "object",
      additionalProperties: false,
      required: [
        "sessionId",
        "userId",
        "agentId",
        "rootEntityId",
        "taskScope",
      ],
      properties: {
        sessionId: nonEmptyString,
        userId: nonEmptyString,
        agentId: nonEmptyString,
        rootEntityId: nonEmptyString,
        taskScope: { $ref: "#/$defs/TaskScope" },
        delegationId: nonEmptyString,
        parentAgentId: nonEmptyString,
      },
    },
    PermissionSubject: {
      oneOf: [
        {
          type: "object",
          additionalProperties: false,
          required: ["kind", "userId"],
          properties: {
            kind: { const: "user" },
            userId: nonEmptyString,
          },
        },
        {
          type: "object",
          additionalProperties: false,
          required: ["kind", "agentId", "ownerUserId"],
          properties: {
            kind: { const: "agent" },
            agentId: nonEmptyString,
            ownerUserId: nonEmptyString,
          },
        },
      ],
    },
    PermissionRequest: {
      type: "object",
      additionalProperties: false,
      required: ["subject", "rootEntityId", "action", "resourceKind"],
      properties: {
        subject: { $ref: "#/$defs/PermissionSubject" },
        rootEntityId: nonEmptyString,
        action: { $ref: "#/$defs/MemoryAction" },
        resourceKind: { $ref: "#/$defs/MemoryObjectKind" },
        branchRef: nonEmptyString,
        entityId: nonEmptyString,
        resourceId: nonEmptyString,
        tags: stringArray,
        relationType: { $ref: "#/$defs/MemoryRelationType" },
        relationDepth: { type: "integer", minimum: 0 },
        taskScope: { $ref: "#/$defs/TaskScope" },
      },
    },
    PermissionDecision: {
      type: "object",
      additionalProperties: false,
      required: [
        "allowed",
        "reason",
        "subjectId",
        "subjectKind",
        "rootEntityId",
        "action",
        "resourceKind",
        "matchedRoles",
        "missingActions",
        "constraints",
      ],
      properties: {
        allowed: { type: "boolean" },
        reason: nonEmptyString,
        subjectId: nonEmptyString,
        subjectKind: { enum: ["user", "agent"] },
        rootEntityId: nonEmptyString,
        action: { $ref: "#/$defs/MemoryAction" },
        resourceKind: { $ref: "#/$defs/MemoryObjectKind" },
        matchedRoles: stringArray,
        missingActions: {
          type: "array",
          items: { $ref: "#/$defs/MemoryAction" },
          uniqueItems: true,
        },
        constraints: { $ref: "#/$defs/PermissionConstraint" },
      },
    },
    MemoryRelationEndpoint: {
      type: "object",
      additionalProperties: false,
      required: ["target", "name"],
      properties: {
        target: {
          enum: [
            "memory_entity",
            "memory_entity_branch",
            "resource",
            "resource_chunk",
          ],
        },
        name: nonEmptyString,
        parent: nonEmptyString,
      },
    },
    MemoryCaptureOperationProperties: {
      type: "object",
      additionalProperties: false,
      properties: {
        name: nonEmptyString,
        desc: { type: "string" },
        tags: stringArray,
        status: { type: "string" },
        extra: { type: "object" },
      },
    },
    MemoryCaptureOperation: {
      oneOf: [
        {
          type: "object",
          additionalProperties: false,
          required: ["target", "op", "properties"],
          properties: {
            target: { const: "memory_entity" },
            op: { enum: ["create", "update", "refresh"] },
            properties: {
              $ref: "#/$defs/MemoryCaptureOperationProperties",
            },
          },
        },
        {
          type: "object",
          additionalProperties: false,
          required: ["target", "op", "subject", "properties"],
          properties: {
            target: { const: "memory_entity_branch" },
            op: { enum: ["create", "update_metadata"] },
            subject: {
              oneOf: [
                nonEmptyString,
                { $ref: "#/$defs/MemoryRelationEndpoint" },
              ],
            },
            properties: {
              $ref: "#/$defs/MemoryCaptureOperationProperties",
            },
          },
        },
        {
          type: "object",
          additionalProperties: false,
          required: ["target", "op", "type", "subject", "object"],
          properties: {
            target: { const: "memory_relation" },
            op: { enum: ["create", "replace"] },
            type: { $ref: "#/$defs/MemoryRelationType" },
            subject: { $ref: "#/$defs/MemoryRelationEndpoint" },
            object: { $ref: "#/$defs/MemoryRelationEndpoint" },
          },
        },
      ],
    },
    AgentFacingCaptureInput: {
      type: "object",
      additionalProperties: false,
      required: ["operations"],
      properties: {
        operations: {
          type: "array",
          minItems: 1,
          items: { $ref: "#/$defs/MemoryCaptureOperation" },
        },
      },
    },
    MemorySearchInput: {
      type: "object",
      additionalProperties: false,
      required: ["query"],
      properties: {
        query: nonEmptyString,
        limit: { type: "integer", minimum: 1 },
        layer: { enum: ["L1", "L2", "L3"] },
        names: stringArray,
        tagsAny: {
          ...stringArray,
          description: "Exact visible tag strings copied from memory.catalog; these are filters, not inferred keywords.",
        },
      },
    },
    MemoryCatalogInput: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    MemoryCatalogResult: {
      type: "object",
      additionalProperties: false,
      required: ["rootName", "branchRef", "entities", "tags"],
      properties: {
        rootName: nonEmptyString,
        branchRef: nonEmptyString,
        entities: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["name", "summary", "status", "tags"],
            properties: {
              name: nonEmptyString,
              summary: { type: "string" },
              status: { type: "string" },
              tags: stringArray,
            },
          },
        },
        tags: {
          ...stringArray,
          description: "Plain visible tag strings sorted by descending visible entity count, with deterministic tag-name ordering for ties. Counts and per-tag entity names are not exposed.",
        },
      },
    },
    HostLifecycleCaptureResult: {
      type: "object",
      additionalProperties: false,
      required: [
        "status",
        "resourceId",
        "revisionId",
        "chunkIds",
        "extractionCandidates",
        "commitIds",
        "extra",
      ],
      properties: {
        status: { const: "captured" },
        resourceId: nonEmptyString,
        revisionId: nonEmptyString,
        chunkIds: {
          type: "array",
          items: nonEmptyString,
          uniqueItems: true,
        },
        extractionCandidates: {
          type: "array",
          items: { $ref: "#/$defs/MemoryCaptureOperation" },
        },
        commitIds: {
          type: "array",
          items: nonEmptyString,
          uniqueItems: true,
        },
        extra: { type: "object" },
      },
    },
    MemoryEntity: {
      type: "object",
      additionalProperties: false,
      required: ["id", "rootEntityId", "status", "createdAt", "updatedAt"],
      properties: {
        id: nonEmptyString,
        rootEntityId: {
          anyOf: [nonEmptyString, { type: "null" }],
        },
        status: {
          enum: ["active", "archived", "tombstoned", "conflicted"],
        },
        currentBranchId: nonEmptyString,
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    MemoryEntityBranch: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "entityId",
        "rootEntityId",
        "branchRef",
        "title",
        "description",
        "tags",
        "importance",
        "confidence",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        entityId: nonEmptyString,
        rootEntityId: nonEmptyString,
        branchRef: nonEmptyString,
        parentBranchId: nonEmptyString,
        title: { type: "string" },
        description: { type: "string" },
        tags: stringArray,
        extraInfo: {
          type: "object",
          propertyNames: {
            not: {
              enum: RELATIONSHIP_EXTRA_INFO_KEYS,
            },
          },
        },
        importance: { type: "number" },
        confidence: { type: "number" },
        status: {
          enum: [
            "active",
            "pending",
            "conflicted",
            "deprecated",
            "verified",
            "superseded",
            "tombstoned",
          ],
        },
        origin: {
          enum: ["cloud_snapshot", "local_pending", "resolution", "import"],
        },
        pendingId: { anyOf: [nonEmptyString, { type: "null" }] },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    MemoryRelation: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "rootEntityId",
        "sourceId",
        "sourceKind",
        "targetId",
        "targetKind",
        "relationType",
        "weight",
        "confidence",
        "branchRef",
        "status",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        rootEntityId: nonEmptyString,
        sourceId: nonEmptyString,
        sourceKind: {
          enum: relationEndpointKinds,
        },
        targetId: nonEmptyString,
        targetKind: {
          enum: relationEndpointKinds,
        },
        relationType: { $ref: "#/$defs/MemoryRelationType" },
        role: nonEmptyString,
        ordinal: { type: "integer", minimum: 0 },
        required: { type: "boolean" },
        condition: { type: "object" },
        weight: { type: "number" },
        confidence: { type: "number" },
        branchRef: nonEmptyString,
        status: {
          enum: ["active", "tombstoned", "conflicted"],
        },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    Resource: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "rootEntityId",
        "sourceType",
        "title",
        "contentHash",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        rootEntityId: nonEmptyString,
        sourceType: {
          enum: [
            "document",
            "conversation",
            "code_repo",
            "code_file",
            "tool_output",
            "webpage",
            "ticket",
            "database_record",
          ],
        },
        title: { type: "string" },
        uri: { type: "string" },
        contentHash: nonEmptyString,
        currentRevisionId: nonEmptyString,
        status: { enum: ["active", "tombstoned"] },
        metadata: { type: "object" },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    ResourceChunk: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "rootEntityId",
        "resourceId",
        "chunkIndex",
        "text",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        rootEntityId: nonEmptyString,
        resourceId: nonEmptyString,
        chunkIndex: { type: "integer", minimum: 0 },
        text: { type: "string" },
        bm25DocumentId: nonEmptyString,
        contentHash: nonEmptyString,
        headingPath: {
          type: "array",
          items: { type: "string" },
        },
        filePath: { type: "string" },
        startLine: { type: "integer", minimum: 1 },
        endLine: { type: "integer", minimum: 1 },
        tokenCount: { type: "integer", minimum: 0 },
        origin: {
          enum: ["cloud_snapshot", "local_pending", "resolution", "import"],
        },
        pendingId: { anyOf: [nonEmptyString, { type: "null" }] },
        status: { enum: ["active", "tombstoned"] },
        metadata: {
          type: "object",
          additionalProperties: true,
          properties: {
            headingPath: {
              type: "array",
              items: { type: "string" },
            },
            filePath: { type: "string" },
            startLine: { type: "integer", minimum: 1 },
            endLine: { type: "integer", minimum: 1 },
            tokenCount: { type: "integer", minimum: 0 },
            revisionId: nonEmptyString,
            contentHash: nonEmptyString,
          },
        },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    ResourceRevision: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "resourceId",
        "rootEntityId",
        "commitId",
        "contentHash",
        "createdAt",
      ],
      properties: {
        id: nonEmptyString,
        resourceId: nonEmptyString,
        rootEntityId: nonEmptyString,
        commitId: nonEmptyString,
        parentRevisionId: nonEmptyString,
        contentHash: nonEmptyString,
        metadata: { type: "object" },
        createdAt: timestamp,
      },
    },
    MemoryActor: {
      type: "object",
      additionalProperties: false,
      required: ["kind", "id"],
      properties: {
        kind: { enum: ["user", "agent"] },
        id: nonEmptyString,
      },
    },
    MemoryBranch: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "rootEntityId",
        "branchRef",
        "status",
        "createdAt",
        "updatedAt",
      ],
      properties: {
        id: nonEmptyString,
        rootEntityId: nonEmptyString,
        branchRef: nonEmptyString,
        headCommitId: nonEmptyString,
        status: { enum: ["active", "archived"] },
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    },
    MemoryCommit: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "rootEntityId",
        "branchRef",
        "operationIds",
        "actor",
        "createdAt",
      ],
      properties: {
        id: nonEmptyString,
        rootEntityId: nonEmptyString,
        branchRef: nonEmptyString,
        parentCommitId: nonEmptyString,
        operationIds: {
          type: "array",
          minItems: 1,
          items: nonEmptyString,
          uniqueItems: true,
        },
        actor: { $ref: "#/$defs/MemoryActor" },
        message: { type: "string" },
        createdAt: timestamp,
      },
    },
    MemoryOperationKind: {
      type: "string",
      enum: MEMORY_OPERATION_KINDS,
    },
    MemoryOperation: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "rootEntityId",
        "branchRef",
        "commitId",
        "kind",
        "actor",
        "input",
        "createdAt",
      ],
      properties: {
        id: nonEmptyString,
        rootEntityId: nonEmptyString,
        branchRef: nonEmptyString,
        commitId: nonEmptyString,
        kind: { $ref: "#/$defs/MemoryOperationKind" },
        actor: { $ref: "#/$defs/MemoryActor" },
        provenance: {
          type: "object",
          additionalProperties: false,
          properties: {
            sessionId: nonEmptyString,
            ownerUserId: nonEmptyString,
            delegationId: nonEmptyString,
            parentAgentId: nonEmptyString,
          },
        },
        input: {
          type: "object",
          required: ["kind", "id"],
          properties: {
            kind: { $ref: "#/$defs/MemoryOperationKind" },
            id: nonEmptyString,
          },
        },
        createdAt: timestamp,
      },
    },
  },
} as const;
